### ISSUE TITLE
Font Awesome Issue

### ISSUE THREAD

**Issue by oldmanumby** [N-Parsons/grav-plugin-file-browser#15]
When I activate "Load Font Awesome Free" all is well except it seems to turn my Font Awesome menu items invisible. When I deactivate it, the menu items return to normal, but then there are no icons in the File Browser.

Suggestions?

**Comment by N-Parsons** [comment]
Hi @Umbyology,

It could be a conflict between Font Awesome 4 and 5 - if that's the case, I should be able to add support in to resolve the issue.

How are you loading Font Awesome for your menus and which version are you using? If it's loaded as part of your theme, which theme are you using?

**Comment by oldmanumby** [comment]
RocketTheme's Manticore theme. However, I've since dropped this direction for now. Currently working on a new website, but I will keep you informed if I see issues still. THX!

**Comment by N-Parsons** [comment]
Thanks for the details. Since I don't have access to that theme I can't test it directly, but I was able to successfully use FA4 icons loaded via the Quark theme on the same page as the File Browser with FA5 being loaded by this plugin.

Regardless, I've just released v0.2.7, which improves support for FA4 in the file browser, providing a solution for anyone either encountering this issue or just wanting to use FA4.
